# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_sensors_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor_types',
            field=models.CharField(choices=[('sw', 'On off switch'), ('ou', 'Sensor output'), ('sl', 'Data slider')], default='sw', max_length=2),
        ),
    ]
