# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensors_sensor_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='created_at',
        ),
    ]
