# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20170216_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensors',
            options={'ordering': ['-created'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AddField(
            model_name='sensors',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
