# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20170216_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='auth.Group'),
        ),
    ]
