# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_auto_20170227_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='Category',
            new_name='categori',
        ),
    ]
