# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20170227_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='category',
            new_name='owner',
        ),
    ]
