# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_categories_owner'),
        ('sensors', '0013_auto_20170227_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Categories'),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
