# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_auto_20170227_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='category',
        ),
        migrations.AlterField(
            model_name='sensors',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='categories.Categories'),
        ),
    ]
