# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_auto_20170228_1102'),
        ('sensors', '0010_auto_20170227_1529'),
    ]

    operations = [
    ]
