# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_merge_20170228_1108'),
        ('sensors', '0016_merge_20170228_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensors',
            name='owner',
        ),
        migrations.AddField(
            model_name='sensors',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='categories.Categories'),
        ),
    ]
