# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
        ('sensors', '0018_sensors_gpio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='controllers.Controllers'),
        ),
    ]
