# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Controller',
                'verbose_name_plural': 'Controllers',
            },
        ),
    ]
