# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0004_remove_categories_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
