# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categories_users'),
        ('categories', '0005_categories_owner'),
    ]

    operations = [
    ]
