# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0003_auto_20170525_1754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensors', '0020_sensors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('controllers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controllers.Controllers')),
                ('sensors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensors')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
    ]
