# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgets',
            name='controllers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controllers.Controllers'),
        ),
    ]
