# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_auto_20170612_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgets',
            name='widget_type',
            field=models.CharField(blank=True, choices=[('clock', 'Clock'), ('weather', 'Weather')], max_length=2, null=True),
        ),
    ]
