# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_widgets_widget_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgets',
            name='title',
        ),
        migrations.AlterField(
            model_name='widgets',
            name='sensors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensors'),
        ),
        migrations.AlterField(
            model_name='widgets',
            name='widget_type',
            field=models.CharField(blank=True, choices=[('CL', 'Clock'), ('WE', 'Weather')], max_length=2, null=True),
        ),
    ]
